"""new database migration

Revision ID: 0c0c71ff13e4
Revises: 400faf988bbd
Create Date: 2019-12-16 10:31:24.614516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c0c71ff13e4'
down_revision = '400faf988bbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reference',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_paper', sa.Integer(), nullable=True),
    sa.Column('to_paper', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reference')
    # ### end Alembic commands ###
