"""my database migration

Revision ID: 36575ef0bd25
Revises: 922a1d254dce
Create Date: 2020-01-09 14:46:29.615037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36575ef0bd25'
down_revision = '922a1d254dce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('write',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paper', sa.String(length=42), nullable=True),
    sa.Column('author', sa.String(length=42), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('write')
    # ### end Alembic commands ###
