"""my database migration

Revision ID: 400faf988bbd
Revises: f059b0bae61f
Create Date: 2019-12-14 22:11:51.276276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '400faf988bbd'
down_revision = 'f059b0bae61f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paper', sa.Column('year', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('paper', 'year')
    # ### end Alembic commands ###
