"""empty message

Revision ID: 87106c57074c
Revises: 9d48ba00567c
Create Date: 2020-03-07 16:50:22.104512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87106c57074c'
down_revision = '9d48ba00567c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reference', sa.Column('is_influential', sa.Boolean(), nullable=True))
    op.drop_column('reference', 'isInfluential')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reference', sa.Column('isInfluential', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('reference', 'is_influential')
    # ### end Alembic commands ###
