"""my database migration

Revision ID: 922a1d254dce
Revises: 1131abd876d0
Create Date: 2020-01-09 13:22:14.520030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '922a1d254dce'
down_revision = '1131abd876d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('author',
    sa.Column('id', sa.String(length=42), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('author')
    # ### end Alembic commands ###
